#############################################################################
# Makefile for building: LSys2D
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Oct 11 15:10:07 2009
# Project:  LSys2D.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile LSys2D.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++ -g
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4 -I. -I.
LINK          = g++ -g
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lpthread -lSDL -lGL -lglut tinyxml/*.o
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		point2d.cpp \
		parser.cpp \
		calc.cpp \
		engine/engine.cpp \
		point3d.cpp \
		direction.cpp \
		alphabet.cpp \
		memcache.cpp \
		iterator.cpp \
		stringstat.cpp 
OBJECTS       = main.o \
		point2d.o \
		parser.o \
		calc.o \
		engine.o \
		point3d.o \
		direction.o \
		alphabet.o \
		memcache.o \
		iterator.o \
		stringstat.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		LSys2D.pro
QMAKE_TARGET  = LSys2D
DESTDIR       = 
TARGET        = LSys2D

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LSys2D.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile LSys2D.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile LSys2D.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LSys2D1.0.0 || $(MKDIR) .tmp/LSys2D1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LSys2D1.0.0/ && $(COPY_FILE) --parents point2d.h parser.h calc.h engine/engine.h point3d.h direction.h alphabet.h memcache.h iterator.h stringstat.h .tmp/LSys2D1.0.0/ && $(COPY_FILE) --parents main.cpp point2d.cpp parser.cpp calc.cpp engine/engine.cpp point3d.cpp direction.cpp alphabet.cpp memcache.cpp iterator.cpp stringstat.cpp .tmp/LSys2D1.0.0/ && (cd `dirname .tmp/LSys2D1.0.0` && $(TAR) LSys2D1.0.0.tar LSys2D1.0.0 && $(COMPRESS) LSys2D1.0.0.tar) && $(MOVE) `dirname .tmp/LSys2D1.0.0`/LSys2D1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LSys2D1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp parser.h \
		alphabet.h \
		calc.h \
		engine/engine.h \
		point3d.h \
		memcache.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

point2d.o: point2d.cpp point2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point2d.o point2d.cpp

parser.o: parser.cpp parser.h \
		alphabet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser.cpp

calc.o: calc.cpp calc.h \
		engine/engine.h \
		point3d.h \
		parser.h \
		alphabet.h \
		memcache.h \
		direction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calc.o calc.cpp

engine.o: engine/engine.cpp engine/engine.h \
		point3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o engine.o engine/engine.cpp

point3d.o: point3d.cpp point3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point3d.o point3d.cpp

direction.o: direction.cpp direction.h \
		point3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o direction.o direction.cpp

alphabet.o: alphabet.cpp alphabet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alphabet.o alphabet.cpp

memcache.o: memcache.cpp memcache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memcache.o memcache.cpp

iterator.o: iterator.cpp iterator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iterator.o iterator.cpp

stringstat.o: stringstat.cpp stringstat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stringstat.o stringstat.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

